name: Build and test
# run on push for all branches
on:
  push:
    # branches: [ "main" ]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:39

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install dependencies
        run: |
          sudo dnf install -y gtk4-devel gcc openssl-devel
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
