name: Rust
# run on push for all branches
on:
  push:
    # branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install/Update gtk
      run: sudo apt install libglib2.0-dev libgtk-4-dev build-essential
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
